
name: test-api
appName: test
namespace: test-dev
replicas: 1
image: ghcr.io/ficox/test-api:dev-latest
port: 8000
resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"
healthPath: "/health"