
name: test-ui
appName: test
namespace: test-prod
replicas: 1
image: ghcr.io/ficox/test-ui:prod-latest
port: 80
resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"
healthPath: "/"