apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels: { app: {{ .Values.name  }} }
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels: { app: {{ .Values.name  }} }
  template:
    metadata:
      labels: { app: {{ .Values.name  }} }
    spec:
      replicas: {{ .Values.replicas }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: {{ .Values.healthPath }}
              port: {{ .Values.port }}
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: {{ .Values.healthPath }}
              port: {{ .Values.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          ports:
            - containerPort: {{ .Values.port }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          volumeMounts:
            - name: api-data
              mountPath: /data
      volumes:
        - name: api-data
          persistentVolumeClaim:
            claimName: {{ .Values.appName }}-api-data-pvc
